Repository Tesssssssssy/campingOnTop_Refactoring-Backend, pull requests merged in 2024-08, with the labels that each got.

#25 [Chore] domain 변수 처리 추가
  src/main/java/com/example/campingontop/config/filter/CorsFilter.java
  src/main/java/com/example/campingontop/domain/mysql/user/service/UserService.java
Labels: Backend, Modification

#26 [Feat] 쿠폰 기능에 스케줄러 도입, 오전 1시에 자동 폐기 (#14)
  src/main/java/com/example/campingontop/domain/mysql/coupon/constant/Event.java
  src/main/java/com/example/campingontop/domain/mysql/coupon/model/Coupon.java
  src/main/java/com/example/campingontop/domain/mysql/coupon/repository/CouponRepository.java
  src/main/java/com/example/campingontop/domain/mysql/coupon/repository/queryDsl/CouponRepositoryCustom.java
  src/main/java/com/example/campingontop/domain/mysql/coupon/repository/queryDsl/CouponRepositoryCustomImpl.java
  src/main/java/com/example/campingontop/domain/mysql/coupon/scheduler/EventScheduler.java
  src/main/java/com/example/campingontop/domain/mysql/coupon/service/CouponService.java
  src/main/java/com/example/campingontop/domain/mysql/orders/controller/OrdersController.java
  src/main/java/com/example/campingontop/domain/mysql/orders/service/OrdersService.java
  src/main/java/com/example/campingontop/domain/mysql/review/model/response/GetFindReviewByUserIdDtoRes.java
  src/main/java/com/example/campingontop/domain/mysql/review/service/ReviewService.java
  src/main/java/com/example/campingontop/domain/mysql/userCoupon/model/UserCoupon.java
  src/main/java/com/example/campingontop/domain/mysql/userCoupon/repository/UserCouponRepository.java
  src/main/java/com/example/campingontop/exception/ErrorCode.java
  src/main/java/com/example/campingontop/exception/GlobalExceptionAdvise.java
  src/main/java/com/example/campingontop/exception/entityException/CouponException.java
Labels: Backend, New Function, Refactoring

#27 [Fix] 로그인 에러 처리
  src/main/java/com/example/campingontop/domain/mysql/user/service/UserService.java
  src/main/java/com/example/campingontop/exception/ErrorCode.java
Labels: Backend, Modification

#28 [Docs] README.md 수정
  README.md
Labels: Backend

#29 [Fix] 작성한 리뷰 보이지 않는 에러 해결
  src/main/java/com/example/campingontop/domain/mysql/review/repository/queryDsl/ReviewRepositoryCustomImpl.java
Labels: Backend, Modification
